#!/bin/bash

set -e

FLAVOR="Mobile"
if [ $1 ]
  then
    FLAVOR=$1
fi

TASK="install$(tr '[:lower:]' '[:upper:]' <<< ${FLAVOR:0:1})${FLAVOR:1}Debug"

#./go

#if [ "$?" -eq 0 ]; then
#    echo "GO BUILD OK."
    echo $TASK
    ./gradlew $TASK

    if [ "$?" -eq 0 ]; then
        echo "ANDROID BUILD OK."
        adb shell am start -n "com.ferg.afergulator/com.ferg.afergulator.MainActivity" \
            -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
    else
        echo "-- ANDROID BUILD ERROR --"
        cat android/.build_log
        echo "^^ ANDROID BUILD ERROR ^^"
    fi
#fi
